
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - =kubeflow.org
  resources:
  - notebooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks/status
  - notebooks
  - '*'
  verbs:
  - get
  - patch
  - update
  - list
  - watch
  - delete
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - events
  verbs:
  - list
  - get
  - watch
  - update
  - delete
  - create
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - "*"
